# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079ca2d129ee5aa06742b45185c0aab6832c9fdd1d1406f04198728264a9ba06c1a8ad14aa500dd2bd5ce30a8a075338f0de6254d11c5d1aff1adfd4c9dea322

test:
  secret_key_base: dce104faba0406b90ce94843d3e6063fdea12af6dd9842917b0e2cebd93a659c109c7c694640ddb8bda9320b9c937c11fca892e853b576fbe9bc6847e23f3420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
